### ISSUE TITLE
support for non-transition

### ISSUE THREAD

**Issue by yuheiy** [yuheiy/animated-collapse-element#1]
use case:

```css
@media (prefers-reduced-motion: reduce) {
  :root {
    --animated-collapse-duration-expand: 0s;
    --animated-collapse-duration-collapse: 0s;
  }
}
```
